import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { ReleaseCard, Tag } from "@/components/sonicbase";
import { releases } from "@/lib/sonicbase-data";

export const Route = createFileRoute("/music/$release")({ loader: ({ params }) => { const release = releases.find((r) => r.slug === params.release); if (!release) throw notFound(); return release; }, head: ({ loaderData }) => ({ meta: [
  { title: `${loaderData?.title ?? "Release"} — Sonicbase` }, { name: "description", content: loaderData?.description ?? "A Sonicbase release." },
  { property: "og:title", content: `${loaderData?.title ?? "Release"} — Sonicbase` }, { property: "og:description", content: loaderData?.description ?? "A Sonicbase release." },
  { property: "og:type", content: "music.album" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ReleasePage });

function ReleasePage() { const release = Route.useLoaderData(); const related = releases.filter((r) => r.slug !== release.slug).slice(0,2); return <><section className="page-shell grid gap-10 pb-24 pt-12 lg:grid-cols-2 lg:items-end"><img src={release.image} alt={`${release.title} artwork`} width={1536} height={1536} className="aspect-square w-full rounded-[7px] object-cover" /><div className="pb-3"><Tag>{release.type}</Tag><h1 className="display-title mt-6 text-6xl sm:text-8xl">{release.title}</h1><Link to="/artists/$artist" params={{ artist: release.artistSlug }} className="mt-4 block text-2xl font-bold">{release.artist}</Link><p className="mt-8 max-w-lg text-lg text-muted-foreground">{release.description}</p><p className="mt-6 text-sm">{release.date}</p><div className="mt-8 flex flex-wrap gap-2"><Button size="lg">Listen now</Button><Button size="lg" variant="outline">Buy</Button></div></div></section><section className="bg-primary text-primary-foreground"><div className="page-shell grid gap-12 py-24 lg:grid-cols-2"><h2 className="display-title text-5xl">Track listing</h2><ol>{release.tracks.map((track, i) => <li key={track} className="grid grid-cols-[2rem_1fr_auto] border-b border-primary-foreground/25 py-4"><span className="text-primary-foreground/50">{String(i+1).padStart(2,"0")}</span><span>{track}</span><span className="text-primary-foreground/50">•••</span></li>)}</ol></div></section><section className="page-shell py-24"><h2 className="display-title text-5xl">More music</h2><div className="mt-10 grid grid-cols-2 gap-3">{related.map((r) => <ReleaseCard key={r.slug} release={r} />)}</div></section></>; }