/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminArtistsRouteImport } from './routes/admin/artists'
import { Route as AdminMerchandiseRouteImport } from './routes/admin/merchandise'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminReleasesRouteImport } from './routes/admin/releases'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as ArtistIndexRouteImport } from './routes/artist/index'
import { Route as ArtistProfileRouteImport } from './routes/artist/profile'
import { Route as ArtistReleasesRouteImport } from './routes/artist/releases'
import { Route as ArtistRevenueRouteImport } from './routes/artist/revenue'
import { Route as ArtistStreamsRouteImport } from './routes/artist/streams'
import { Route as ArtistsArtistRouteImport } from './routes/artists.$artist'
import { Route as MusicReleaseRouteImport } from './routes/music.$release'
import { Route as NewsNewsRouteImport } from './routes/news.$news'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as AdminArtistsArtistRouteImport } from './routes/admin/artists/$artist'
import { Route as AdminArtistsNewRouteImport } from './routes/admin/artists/new'
import { Route as AdminMerchandiseNewRouteImport } from './routes/admin/merchandise/new'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders.$orderId'
import { Route as AdminReleasesReleaseRouteImport } from './routes/admin/releases/$release'
import { Route as AdminReleasesNewRouteImport } from './routes/admin/releases/new'
import { Route as ArtistReleasesReleaseRouteImport } from './routes/artist/releases/$release'
import { Route as AdminArtistsArtistEditRouteImport } from './routes/admin/artists/$artist/edit'
import { Route as AdminMerchandiseIdEditRouteImport } from './routes/admin/merchandise/$id/edit'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin/news/$id/edit'
import { Route as AdminReleasesReleaseEditRouteImport } from './routes/admin/releases/$release/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchandiseRoute = AdminMerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReleasesRoute = AdminReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistProfileRoute = ArtistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistReleasesRoute = ArtistReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistRevenueRoute = ArtistRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistStreamsRoute = ArtistStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistsArtistRoute = ArtistsArtistRouteImport.update({
  id: '/$artist',
  path: '/$artist',
  getParentRoute: () => ArtistsRoute,
} as any)
const MusicReleaseRoute = MusicReleaseRouteImport.update({
  id: '/$release',
  path: '/$release',
  getParentRoute: () => MusicRoute,
} as any)
const NewsNewsRoute = NewsNewsRouteImport.update({
  id: '/$news',
  path: '/$news',
  getParentRoute: () => NewsRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const AdminArtistsArtistRoute = AdminArtistsArtistRouteImport.update({
  id: '/$artist',
  path: '/$artist',
  getParentRoute: () => AdminArtistsRoute,
} as any)
const AdminArtistsNewRoute = AdminArtistsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArtistsRoute,
} as any)
const AdminMerchandiseNewRoute = AdminMerchandiseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMerchandiseRoute,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNewsRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminReleasesReleaseRoute = AdminReleasesReleaseRouteImport.update({
  id: '/$release',
  path: '/$release',
  getParentRoute: () => AdminReleasesRoute,
} as any)
const AdminReleasesNewRoute = AdminReleasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminReleasesRoute,
} as any)
const ArtistReleasesReleaseRoute = ArtistReleasesReleaseRouteImport.update({
  id: '/$release',
  path: '/$release',
  getParentRoute: () => ArtistReleasesRoute,
} as any)
const AdminArtistsArtistEditRoute = AdminArtistsArtistEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminArtistsArtistRoute,
} as any)
const AdminMerchandiseIdEditRoute = AdminMerchandiseIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminMerchandiseRoute,
} as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminNewsRoute,
} as any)
const AdminReleasesReleaseEditRoute =
  AdminReleasesReleaseEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminReleasesReleaseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/artist': typeof ArtistRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/merchandise': typeof AdminMerchandiseRouteWithChildren
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/releases': typeof AdminReleasesRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/artist/profile': typeof ArtistProfileRoute
  '/artist/releases': typeof ArtistReleasesRouteWithChildren
  '/artist/revenue': typeof ArtistRevenueRoute
  '/artist/streams': typeof ArtistStreamsRoute
  '/artists/$artist': typeof ArtistsArtistRoute
  '/music/$release': typeof MusicReleaseRoute
  '/news/$news': typeof NewsNewsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/artist/': typeof ArtistIndexRoute
  '/admin/artists/$artist': typeof AdminArtistsArtistRouteWithChildren
  '/admin/artists/new': typeof AdminArtistsNewRoute
  '/admin/merchandise/new': typeof AdminMerchandiseNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/releases/$release': typeof AdminReleasesReleaseRouteWithChildren
  '/admin/releases/new': typeof AdminReleasesNewRoute
  '/artist/releases/$release': typeof ArtistReleasesReleaseRoute
  '/admin/artists/$artist/edit': typeof AdminArtistsArtistEditRoute
  '/admin/merchandise/$id/edit': typeof AdminMerchandiseIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/releases/$release/edit': typeof AdminReleasesReleaseEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/merchandise': typeof AdminMerchandiseRouteWithChildren
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/releases': typeof AdminReleasesRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/artist/profile': typeof ArtistProfileRoute
  '/artist/releases': typeof ArtistReleasesRouteWithChildren
  '/artist/revenue': typeof ArtistRevenueRoute
  '/artist/streams': typeof ArtistStreamsRoute
  '/artists/$artist': typeof ArtistsArtistRoute
  '/music/$release': typeof MusicReleaseRoute
  '/news/$news': typeof NewsNewsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/artist': typeof ArtistIndexRoute
  '/admin/artists/$artist': typeof AdminArtistsArtistRouteWithChildren
  '/admin/artists/new': typeof AdminArtistsNewRoute
  '/admin/merchandise/new': typeof AdminMerchandiseNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/releases/$release': typeof AdminReleasesReleaseRouteWithChildren
  '/admin/releases/new': typeof AdminReleasesNewRoute
  '/artist/releases/$release': typeof ArtistReleasesReleaseRoute
  '/admin/artists/$artist/edit': typeof AdminArtistsArtistEditRoute
  '/admin/merchandise/$id/edit': typeof AdminMerchandiseIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/releases/$release/edit': typeof AdminReleasesReleaseEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/artist': typeof ArtistRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/music': typeof MusicRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/merchandise': typeof AdminMerchandiseRouteWithChildren
  '/admin/news': typeof AdminNewsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/releases': typeof AdminReleasesRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/artist/profile': typeof ArtistProfileRoute
  '/artist/releases': typeof ArtistReleasesRouteWithChildren
  '/artist/revenue': typeof ArtistRevenueRoute
  '/artist/streams': typeof ArtistStreamsRoute
  '/artists/$artist': typeof ArtistsArtistRoute
  '/music/$release': typeof MusicReleaseRoute
  '/news/$news': typeof NewsNewsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/artist/': typeof ArtistIndexRoute
  '/admin/artists/$artist': typeof AdminArtistsArtistRouteWithChildren
  '/admin/artists/new': typeof AdminArtistsNewRoute
  '/admin/merchandise/new': typeof AdminMerchandiseNewRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/releases/$release': typeof AdminReleasesReleaseRouteWithChildren
  '/admin/releases/new': typeof AdminReleasesNewRoute
  '/artist/releases/$release': typeof ArtistReleasesReleaseRoute
  '/admin/artists/$artist/edit': typeof AdminArtistsArtistEditRoute
  '/admin/merchandise/$id/edit': typeof AdminMerchandiseIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/admin/releases/$release/edit': typeof AdminReleasesReleaseEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/artist'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/music'
    | '/news'
    | '/reset-password'
    | '/shop'
    | '/admin/artists'
    | '/admin/merchandise'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/releases'
    | '/admin/revenue'
    | '/artist/profile'
    | '/artist/releases'
    | '/artist/revenue'
    | '/artist/streams'
    | '/artists/$artist'
    | '/music/$release'
    | '/news/$news'
    | '/order/$orderId'
    | '/shop/$productId'
    | '/admin/'
    | '/artist/'
    | '/admin/artists/$artist'
    | '/admin/artists/new'
    | '/admin/merchandise/new'
    | '/admin/news/new'
    | '/admin/orders/$orderId'
    | '/admin/releases/$release'
    | '/admin/releases/new'
    | '/artist/releases/$release'
    | '/admin/artists/$artist/edit'
    | '/admin/merchandise/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/releases/$release/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/music'
    | '/news'
    | '/reset-password'
    | '/shop'
    | '/admin/artists'
    | '/admin/merchandise'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/releases'
    | '/admin/revenue'
    | '/artist/profile'
    | '/artist/releases'
    | '/artist/revenue'
    | '/artist/streams'
    | '/artists/$artist'
    | '/music/$release'
    | '/news/$news'
    | '/order/$orderId'
    | '/shop/$productId'
    | '/admin'
    | '/artist'
    | '/admin/artists/$artist'
    | '/admin/artists/new'
    | '/admin/merchandise/new'
    | '/admin/news/new'
    | '/admin/orders/$orderId'
    | '/admin/releases/$release'
    | '/admin/releases/new'
    | '/artist/releases/$release'
    | '/admin/artists/$artist/edit'
    | '/admin/merchandise/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/releases/$release/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/artist'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/music'
    | '/news'
    | '/reset-password'
    | '/shop'
    | '/admin/artists'
    | '/admin/merchandise'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/releases'
    | '/admin/revenue'
    | '/artist/profile'
    | '/artist/releases'
    | '/artist/revenue'
    | '/artist/streams'
    | '/artists/$artist'
    | '/music/$release'
    | '/news/$news'
    | '/order/$orderId'
    | '/shop/$productId'
    | '/admin/'
    | '/artist/'
    | '/admin/artists/$artist'
    | '/admin/artists/new'
    | '/admin/merchandise/new'
    | '/admin/news/new'
    | '/admin/orders/$orderId'
    | '/admin/releases/$release'
    | '/admin/releases/new'
    | '/artist/releases/$release'
    | '/admin/artists/$artist/edit'
    | '/admin/merchandise/$id/edit'
    | '/admin/news/$id/edit'
    | '/admin/releases/$release/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistRoute: typeof ArtistRouteWithChildren
  ArtistsRoute: typeof ArtistsRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MusicRoute: typeof MusicRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  OrderOrderIdRoute: typeof OrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchandise': {
      id: '/admin/merchandise'
      path: '/merchandise'
      fullPath: '/admin/merchandise'
      preLoaderRoute: typeof AdminMerchandiseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/releases': {
      id: '/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AdminReleasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/profile': {
      id: '/artist/profile'
      path: '/profile'
      fullPath: '/artist/profile'
      preLoaderRoute: typeof ArtistProfileRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/releases': {
      id: '/artist/releases'
      path: '/releases'
      fullPath: '/artist/releases'
      preLoaderRoute: typeof ArtistReleasesRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/revenue': {
      id: '/artist/revenue'
      path: '/revenue'
      fullPath: '/artist/revenue'
      preLoaderRoute: typeof ArtistRevenueRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/streams': {
      id: '/artist/streams'
      path: '/streams'
      fullPath: '/artist/streams'
      preLoaderRoute: typeof ArtistStreamsRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artists/$artist': {
      id: '/artists/$artist'
      path: '/$artist'
      fullPath: '/artists/$artist'
      preLoaderRoute: typeof ArtistsArtistRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/music/$release': {
      id: '/music/$release'
      path: '/$release'
      fullPath: '/music/$release'
      preLoaderRoute: typeof MusicReleaseRouteImport
      parentRoute: typeof MusicRoute
    }
    '/news/$news': {
      id: '/news/$news'
      path: '/$news'
      fullPath: '/news/$news'
      preLoaderRoute: typeof NewsNewsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/artists/$artist': {
      id: '/admin/artists/$artist'
      path: '/$artist'
      fullPath: '/admin/artists/$artist'
      preLoaderRoute: typeof AdminArtistsArtistRouteImport
      parentRoute: typeof AdminArtistsRoute
    }
    '/admin/artists/new': {
      id: '/admin/artists/new'
      path: '/new'
      fullPath: '/admin/artists/new'
      preLoaderRoute: typeof AdminArtistsNewRouteImport
      parentRoute: typeof AdminArtistsRoute
    }
    '/admin/merchandise/new': {
      id: '/admin/merchandise/new'
      path: '/new'
      fullPath: '/admin/merchandise/new'
      preLoaderRoute: typeof AdminMerchandiseNewRouteImport
      parentRoute: typeof AdminMerchandiseRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminNewsRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/releases/$release': {
      id: '/admin/releases/$release'
      path: '/$release'
      fullPath: '/admin/releases/$release'
      preLoaderRoute: typeof AdminReleasesReleaseRouteImport
      parentRoute: typeof AdminReleasesRoute
    }
    '/admin/releases/new': {
      id: '/admin/releases/new'
      path: '/new'
      fullPath: '/admin/releases/new'
      preLoaderRoute: typeof AdminReleasesNewRouteImport
      parentRoute: typeof AdminReleasesRoute
    }
    '/artist/releases/$release': {
      id: '/artist/releases/$release'
      path: '/$release'
      fullPath: '/artist/releases/$release'
      preLoaderRoute: typeof ArtistReleasesReleaseRouteImport
      parentRoute: typeof ArtistReleasesRoute
    }
    '/admin/artists/$artist/edit': {
      id: '/admin/artists/$artist/edit'
      path: '/edit'
      fullPath: '/admin/artists/$artist/edit'
      preLoaderRoute: typeof AdminArtistsArtistEditRouteImport
      parentRoute: typeof AdminArtistsArtistRoute
    }
    '/admin/merchandise/$id/edit': {
      id: '/admin/merchandise/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/merchandise/$id/edit'
      preLoaderRoute: typeof AdminMerchandiseIdEditRouteImport
      parentRoute: typeof AdminMerchandiseRoute
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof AdminNewsRoute
    }
    '/admin/releases/$release/edit': {
      id: '/admin/releases/$release/edit'
      path: '/edit'
      fullPath: '/admin/releases/$release/edit'
      preLoaderRoute: typeof AdminReleasesReleaseEditRouteImport
      parentRoute: typeof AdminReleasesReleaseRoute
    }
  }
}

interface AdminArtistsArtistRouteChildren {
  AdminArtistsArtistEditRoute: typeof AdminArtistsArtistEditRoute
}

const AdminArtistsArtistRouteChildren: AdminArtistsArtistRouteChildren = {
  AdminArtistsArtistEditRoute: AdminArtistsArtistEditRoute,
}

const AdminArtistsArtistRouteWithChildren =
  AdminArtistsArtistRoute._addFileChildren(AdminArtistsArtistRouteChildren)

interface AdminArtistsRouteChildren {
  AdminArtistsArtistRoute: typeof AdminArtistsArtistRouteWithChildren
  AdminArtistsNewRoute: typeof AdminArtistsNewRoute
}

const AdminArtistsRouteChildren: AdminArtistsRouteChildren = {
  AdminArtistsArtistRoute: AdminArtistsArtistRouteWithChildren,
  AdminArtistsNewRoute: AdminArtistsNewRoute,
}

const AdminArtistsRouteWithChildren = AdminArtistsRoute._addFileChildren(
  AdminArtistsRouteChildren,
)

interface AdminMerchandiseRouteChildren {
  AdminMerchandiseNewRoute: typeof AdminMerchandiseNewRoute
  AdminMerchandiseIdEditRoute: typeof AdminMerchandiseIdEditRoute
}

const AdminMerchandiseRouteChildren: AdminMerchandiseRouteChildren = {
  AdminMerchandiseNewRoute: AdminMerchandiseNewRoute,
  AdminMerchandiseIdEditRoute: AdminMerchandiseIdEditRoute,
}

const AdminMerchandiseRouteWithChildren =
  AdminMerchandiseRoute._addFileChildren(AdminMerchandiseRouteChildren)

interface AdminNewsRouteChildren {
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
}

const AdminNewsRouteChildren: AdminNewsRouteChildren = {
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
}

const AdminNewsRouteWithChildren = AdminNewsRoute._addFileChildren(
  AdminNewsRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminReleasesReleaseRouteChildren {
  AdminReleasesReleaseEditRoute: typeof AdminReleasesReleaseEditRoute
}

const AdminReleasesReleaseRouteChildren: AdminReleasesReleaseRouteChildren = {
  AdminReleasesReleaseEditRoute: AdminReleasesReleaseEditRoute,
}

const AdminReleasesReleaseRouteWithChildren =
  AdminReleasesReleaseRoute._addFileChildren(AdminReleasesReleaseRouteChildren)

interface AdminReleasesRouteChildren {
  AdminReleasesReleaseRoute: typeof AdminReleasesReleaseRouteWithChildren
  AdminReleasesNewRoute: typeof AdminReleasesNewRoute
}

const AdminReleasesRouteChildren: AdminReleasesRouteChildren = {
  AdminReleasesReleaseRoute: AdminReleasesReleaseRouteWithChildren,
  AdminReleasesNewRoute: AdminReleasesNewRoute,
}

const AdminReleasesRouteWithChildren = AdminReleasesRoute._addFileChildren(
  AdminReleasesRouteChildren,
)

interface AdminRouteChildren {
  AdminArtistsRoute: typeof AdminArtistsRouteWithChildren
  AdminMerchandiseRoute: typeof AdminMerchandiseRouteWithChildren
  AdminNewsRoute: typeof AdminNewsRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReleasesRoute: typeof AdminReleasesRouteWithChildren
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtistsRoute: AdminArtistsRouteWithChildren,
  AdminMerchandiseRoute: AdminMerchandiseRouteWithChildren,
  AdminNewsRoute: AdminNewsRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminReleasesRoute: AdminReleasesRouteWithChildren,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtistReleasesRouteChildren {
  ArtistReleasesReleaseRoute: typeof ArtistReleasesReleaseRoute
}

const ArtistReleasesRouteChildren: ArtistReleasesRouteChildren = {
  ArtistReleasesReleaseRoute: ArtistReleasesReleaseRoute,
}

const ArtistReleasesRouteWithChildren = ArtistReleasesRoute._addFileChildren(
  ArtistReleasesRouteChildren,
)

interface ArtistRouteChildren {
  ArtistProfileRoute: typeof ArtistProfileRoute
  ArtistReleasesRoute: typeof ArtistReleasesRouteWithChildren
  ArtistRevenueRoute: typeof ArtistRevenueRoute
  ArtistStreamsRoute: typeof ArtistStreamsRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
}

const ArtistRouteChildren: ArtistRouteChildren = {
  ArtistProfileRoute: ArtistProfileRoute,
  ArtistReleasesRoute: ArtistReleasesRouteWithChildren,
  ArtistRevenueRoute: ArtistRevenueRoute,
  ArtistStreamsRoute: ArtistStreamsRoute,
  ArtistIndexRoute: ArtistIndexRoute,
}

const ArtistRouteWithChildren =
  ArtistRoute._addFileChildren(ArtistRouteChildren)

interface ArtistsRouteChildren {
  ArtistsArtistRoute: typeof ArtistsArtistRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistRoute: ArtistsArtistRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface MusicRouteChildren {
  MusicReleaseRoute: typeof MusicReleaseRoute
}

const MusicRouteChildren: MusicRouteChildren = {
  MusicReleaseRoute: MusicReleaseRoute,
}

const MusicRouteWithChildren = MusicRoute._addFileChildren(MusicRouteChildren)

interface NewsRouteChildren {
  NewsNewsRoute: typeof NewsNewsRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsNewsRoute: NewsNewsRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistRoute: ArtistRouteWithChildren,
  ArtistsRoute: ArtistsRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MusicRoute: MusicRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  OrderOrderIdRoute: OrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
